force-app/main/default/objects/FAQ_Item__mdt/FAQ_Item__mdt.object-meta.xml
<CustomObject>
    <label>FAQ Item</label>
    <pluralLabel>FAQ Items</pluralLabel>
</CustomObject>

force-app/main/default/objects/FAQ_Item__mdt/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FAQ_Item__mdt/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAQ_Item__mdt/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <label>Ranking</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FAQController.cls
public without sharing class FAQController {
    @AuraEnabled(cacheable=true)
    public static List<FAQ_Item__mdt> getFAQItems() {
      return [SELECT Question__c, Answer__c FROM FAQ_Item__mdt ORDER BY Ranking__c];
      // comment 1
    }

    public static void feature1(){
      
    }

    public static void feature2(){
      
    }

    //fix
    public static void featureA(){
      
    }
    public static void featureB(){
      
    }

    public static void featureE(){
      
    }
    public static void featureF(){
      
    }



}